name: video_thumb_getter
description: A flutter plugin for creating a thumbnail from a local video file or from a video URL.
version: 0.1.2
repository: https://github.com/gabrielginter/video_thumb_getter
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.4+1
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
    # git: https://github.com/kumsumit/plugin_platform_interface.git
  http: ^1.2.1
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  lints: ^3.0.0

flutter:
  plugin:
    implements: video_thumbnail
    platforms:
      android:
        package: xyz.justsoft.video_thumb_getter
        pluginClass: VideoThumbnailPlugin
      ios:
        pluginClass: VideoThumbnailPlugin
      web:
        pluginClass: VideoThumbnailWeb
        fileName: video_thumbnail_web.dart